export const selectors = {
    hamburgerMenu : 'button[data-toggle-menu-target="button"]',
    iconUserMobile : 'button#mobile-menu',
    iconUser : 'g[clip-path="url(#clip0_440_247)"]',
    emailInput : "input#user_email",
    passwordInput : "input#user_password",
    repeatPassword : "input#user_password_confirmation",
    signUpButton : 'div a[href="/user/sign_up"]',
    submit : 'input[type="submit"]',
    errorExplanation : 'div#errorExplanation',
    shopAll : 'a[href="/en/products"]',
    wishedProduct : 'button[data-action="wished-item#add"]',
    whisedIcon : 'a#wishlist-icon',
    priceContainer : 'div[data-plp-variant-picker-target="priceContainer"] p',
    productList : 'div#products',
    productCard : 'div.product-card-inner',
    productName : 'h3.product-card-title',
    favoriteList : 'div#wishlist',
    favoritesListItem : 'div.w-full div',
    favoriteListProductName : 'a[href]',
    favoriteListProductPrice : 'div.w-full div.mt-1 p',
}